services:
  database:
    build: 
      context: ./database
      dockerfile: Dockerfile
    container_name: agendame_db
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data  
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - agendame_network
  
  backend:
    build: 
      context: ./agendame
      dockerfile: Dockerfile
    container_name: agendame_backend
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}

    ports:
      - "3000:3000"
    restart: always
    networks:
      - agendame_network

volumes:
  postgres_data:   
    driver: local

networks:
  agendame_network:
    driver: bridge
